export const LIFT_POSTER = {
  brand: "멈춘자",
  brandEn: "YOUR TRANSITION PARTNER",
  title: "LIFT",
  subtitle: "LIFE ARCHITECTURE",
  line: "지금, 내 삶의 구조를\n다시 설계하는 시간",
  body: "흩어진 조각들을 다시 바라보고\n나에게 균형 있는 구조를 만드는\n단 하루의 세미나입니다.",
  close: "A MORE INTENTIONAL YOU",
  axis: ["PAUSE", "AWARENESS", "TRANSITION", "NEXT"] as const,
  benefitsEyebrow: "KEY BENEFITS",
  benefitsTitle: "이 세미나에서\n얻을 수 있는 것",
  benefits: [
    "내 삶의 구조를 명확히 이해",
    "중요한 가치와 우선순위를 다시 정렬",
    "흩어진 에너지를 모아 실행 방향을 설정",
    "더 도약적인 다음 챕터로 설계",
  ] as const,
  forEyebrow: "IDEAL FOR YOU",
  forTitle: "이런 분께\n추천합니다",
  forItems: [
    "바쁜 일정이지만 방향이 맞는지 점검하고 싶은 분",
    "일과 개인의 균형을 다시 잡고 싶은 분",
    "중요한 전환기(커리어, 관계, 삶의 변화)를 준비 중인 분",
    "지금 삶의 단계에 업그레이드하고 싶은 분",
    "더 나은 선택을 위해 멈추고 생각할 시간이 필요한 분",
  ] as const,
  footTitle: "LIFT LIFE ARCHITECTURE",
  footCta: "세미나 신청하기",
  footLead: "간단한 진단 후,\n지금 바로 신청할 수 있습니다.",
  qrHref: "https://meomchunja.com/pause",
  qrLabel: "사전 진단하고 신청하기",
  steps: [
    "사전 진단 (약 3분)",
    "결과 확인",
    "세미나 신청 (선착순 6명 내외)",
  ] as const,
} as const;
